### ISSUE TITLE
VueJS 3 compatible?

### ISSUE THREAD

**Issue by picks44** [guastallaigor/vue-horizontal-timeline#75]
Hi there, is this package compatible with VueJS 3?
I'm trying to use it as explained in the doc, but I get some warnings and errors...

**Comment by guastallaigor** [comment]
Hello @picks44 
Unfortunately not yet. All of my OSS projects are still in Vue 2, because I cannot drop Vue 2 support yet.
Also, I've done some research but I couldn't find a good way of providing both Vue 2 and 3 support.
Let's see when they release 2.7, if that can provide good support to both versions.
If you have any idea on how to provide Vue 3 support without dropping Vue 2, let me know.
Thank you.

**Comment by guastallaigor** [comment]
Now has Vue 3 support without dropping Vue 2!
